# Pre-commit hooks configuration for docs
# See https://pre-commit.com for more information

repos:
  # Markdown formatting
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        args: [--wrap, "80"]

  # Markdown quality check
  # need to install node.js
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: bash -c 'npx markdownlint-cli2 --config .markdownlint.json .'
        language: system
        pass_filenames: false

  # UV lock latest version check
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-lock
