name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
      - chore/docs-cicd # for debug

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          # want to use "uv sync --extra docs" but the depencency in pyproject.toml is broken
          uv venv
          uv pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          cd mkdocs # temporary setting

          # want to use "uv run mkdocs gh-deploy --force" but use the following command because the dependency in pyproject.toml is broken
          uv run --no-project --with mkdocs mkdocs-material -- mkdocs gh-deploy --force

          cd .. # temporary setting
